version: '3.8'
services:
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=myStrongPassword12#
    deploy:
      resources:
        reservations:
          cpus: "2"
          memory: 2GB
    volumes:
      - sqldata:/var/opt/mssql

  contacts:
    container_name: contacts
    build:
      context: .
      dockerfile: ./Contacts/Dockerfile
    image: eruulcontactsscr.azurecr.io/contacts
    domainname: 'eruul'
    ports:
      - "80:80"
    restart: on-failure

volumes:
  sqldata:
    driver: azure_file
    driver_opts:
      share_name: sql-volume
      storage_account_name: eruulcontactssa